{{- if .Values.landingPage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-landing-page-deployment
  labels:
    app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
    helm.sh/chart: {{ include "retrotool-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      retrotool: "landing-page-server"
  template:
    metadata:
      labels:
        retrotool: "landing-page-server"
        app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.landingPage.deployment.affinity }}
      affinity: {{- toYaml .Values.landingPage.deployment.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.landingPage.image }}
          imagePullPolicy: {{ .Values.landingPage.imagePullPolicy }}
          ports:
            - containerPort: 3000
              name: lp-port
              protocol: TCP
          env:
            {{- if .Values.landingPage.deployment.containers.app.env }}
              {{- toYaml .Values.landingPage.deployment.containers.app.env | nindent 12 }}
            {{- end }}
            - name: APP_ENDPOINT
              value: http{{ if .Values.certificate.enabled }}s{{ end }}://{{ index .Values.app.hosts 0 }}
            - name: API_ENDPOINT
              value: http://{{ .Release.Name }}-service.{{ .Release.Namespace }}.svc.cluster.local:3000
            - name: FROM_EMAIL
              value: {{ .Values.app.settings.public.email.contact }}
            - name: RECAPTCHA_SITE_KEY
              value: {{ .Values.app.settings.public.recaptcha.site_key }}
            - name: ROOT_URL
              value: http{{ if .Values.certificate.enabled }}s{{ end }}://{{ index .Values.app.hosts 0 }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          readinessProbe:
            httpGet:
              path: {{ .Values.landingPage.deployment.healthEndpoint }}
              port: lp-port
              httpHeaders:
                - name: Host
                  value: {{ index .Values.app.hosts 0 }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.landingPage.deployment.healthEndpoint }}
              port: lp-port
              httpHeaders:
                - name: Host
                  value: {{ index .Values.app.hosts 0 }}
            failureThreshold: 5
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.landingPage.deployment.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml .Values.landingPage.deployment.topologySpreadConstraints | nindent 8 }}
      {{- end }}
{{- end }}
