apiVersion: v2
description: RetroTool - a simple, but powerful tool for remote retrospectives
name: retrotool
version: 1.6.13

dependencies:
  - name: mongodb-replicaset
    repository: https://charts.helm.sh/stable
    version: 3.11.6
    condition: mongodb-replicaset.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.13.2
    condition: redis.enabled
