apiVersion: v2
description: RetroTool - a simple, but powerful tool for remote retrospectives
name: retrotool-chart
version: 1.1.0

dependencies:
  - name: mongodb-replicaset
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 3.11.6
    condition: mongodb-replicaset.enabled
