{{- $type := .Values.database.type -}}
{{- $enabled := and .Values.backup.enabled .Values.backup.daily -}}
{{- if and $enabled (or (eq $type "replicaset") (eq $type "operator")) }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-backup-db-daily
  namespace: velero
spec:
  schedule: "55 0 * * *"
  template:
    labelSelector:
      matchLabels:
      {{- if eq $type "replicaset" }}
        app: mongodb-replicaset
        release: {{ .Release.Name }}
      {{- else if eq $type "operator" }}
        app: mongodb-svc
      {{- end }}
    includedNamespaces:
      - {{ .Release.Namespace }}
    includeClusterResources: true
    snapshotVolumes: true
    storageLocation: {{ .Values.backup.storageLocation }}
    volumeSnapshotLocations:
      - {{ .Values.backup.storageLocation }}
    ttl: 720h0m0s
{{- end }}
