{{- if and (index .Values "mongodb-replicaset" "enabled") (and .Values.backup.enabled .Values.backup.daily) }}
{{- $instance := 0 -}}
{{- if gt (index .Values "mongodb-replicaset" "replicas") 1 -}}
  {{- $instance = 1 -}}
{{- end -}}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}-backup-db-daily
  namespace: velero
spec:
  schedule: 55 0 * * *
  template:
    labelSelector:
      matchLabels:
        app: mongodb-replicaset
        release: {{ .Release.Name }}
        statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-mongodb-replicaset-{{ $instance }}
    includedNamespaces:
      - {{ .Release.Namespace }}
    includeClusterResources: true
    snapshotVolumes: true
    storageLocation: {{ .Values.backup.storageLocation }}
    volumeSnapshotLocations:
      - {{ .Values.backup.storageLocation }}
    ttl: 168h0m0s
    hooks:
      resources:
        - name: lock-filesystem
          pre:
            - exec:
                container: mongodb-replicaset
                command:
                  - mongo
                  - --eval
                  - "rs.stepDown()"
                timeout: 5m
            - exec:
                container: mongodb-replicaset
                command:
                  - mongo
                  - --eval
                  - "printjson(db.fsyncLock())"
                timeout: 5m
          post:
            - exec:
                container: mongodb-replicaset
                command:
                  - mongo
                  - --eval
                  - "printjson(db.fsyncUnlock())"
                onError: Continue
                timeout: 15m
{{- end }}
