apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
    helm.sh/chart: {{ include "retrotool-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      retrotool: "web-server"
  template:
    metadata:
      labels:
        retrotool: "web-server"
        app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.deployment.affinity }}
      affinity: {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nfs.enabled }}
      securityContext:
        fsGroup: 2000
      initContainers:
        - name: nfs-volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:2000 /backgrounds"]
          volumeMounts:
          - name: backgrounds-volume
            mountPath: /backgrounds
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          ports:
            - containerPort: 3000
              name: app-port
              protocol: TCP
          env:
            {{- if .Values.deployment.containers.app.env }}
              {{- toYaml .Values.deployment.containers.app.env | nindent 12 }}
            {{- end }}
            - name: HTTP_FORWARDED_COUNT
              value: '1'
            - name: MONGO_URL
              {{- if eq .Values.database.type "operator" }}
              valueFrom:
                secretKeyRef:
                  name: mongodb-connection
                  key: url
              {{- else }}
              value: {{ include "mongodb.url" . | quote }}
              {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_OPLOG_SETTINGS
              value: {{ include "redis.settings" . | quote }}
            {{- else }}
            - name: MONGO_OPLOG_URL
              {{- if eq .Values.database.type "operator" }}
              valueFrom:
                secretKeyRef:
                  name: mongodb-connection
                  key: oplogUrl
              {{- else }}
              value: {{ include "mongodb.oplog_url" . | quote }}
              {{- end }}
            {{- end }}
            - name: ROOT_URL
              value: "{{ default "https" .Values.app.protocol }}://{{ index .Values.app.hosts 0 }}"
            - name: METEOR_SETTINGS
              value: {{ toJson .Values.app.settings | quote }}
            - name: MAIL_URL
              value: {{ .Values.app.mail.url | quote }}
          {{- if .Values.nfs.enabled }}
          volumeMounts:
            - name: backgrounds-volume
              mountPath: "/backgrounds"
          {{- end }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          readinessProbe:
            httpGet:
              path: /
              port: app-port
              httpHeaders:
                - name: Host
                  value: {{ index .Values.app.hosts 0 }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: app-port
              httpHeaders:
                - name: Host
                  value: {{ index .Values.app.hosts 0 }}
            failureThreshold: 5
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nfs.enabled }}
      volumes:
        - name: backgrounds-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Release.Namespace }}-pvc
      {{- end }}
      {{- if .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml .Values.deployment.topologySpreadConstraints | nindent 8 }}
      {{- end }}
