{{- $date := now | date "2006-01-17_15-04" -}}
{{- $defaultRedisSettings := dict "redis" (dict "host" (printf "%s-local-redis-master" $.Release.Name)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
    helm.sh/chart: {{ include "retrotool-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    deployed-at: {{ $date }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        retrotool: "web-server"
        app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        deployed-at: {{ $date }}
    spec:
      {{- if .Values.deployment.affinity }}
      affinity: {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          ports:
            - containerPort: 3000
              name: app-port
              protocol: TCP
          env:
            {{- if .Values.deployment.containers.app.env }}
              {{- toYaml .Values.deployment.containers.app.env | nindent 12 }}
            {{- end }}
            - name: HTTP_FORWARDED_COUNT
              value: '1'
            - name: MONGO_URL
              value: {{ include "mongodb.replicaset_url" . | quote }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_OPLOG_SETTINGS
              value: {{ mustMerge $defaultRedisSettings .Values.app.redisOplog | toJson | quote }}
            {{- else }}
            - name: MONGO_OPLOG_URL
              value: {{ include "mongodb.replicaset_oplog_url" . | quote }}
            {{- end }}
            - name: ROOT_URL
              value: "{{ default "https" .Values.app.protocol }}://{{ .Values.app.host }}"
            - name: METEOR_SETTINGS
              value: {{ toJson .Values.app.settings | quote }}
            - name: MAIL_URL
              value: {{ .Values.app.mail.url | quote }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          readinessProbe:
            httpGet:
              path: /
              port: app-port
              httpHeaders:
                - name: Host
                  value: {{ .Values.app.host }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: app-port
              httpHeaders:
                - name: Host
                  value: {{ .Values.app.host }}
            failureThreshold: 5
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml .Values.deployment.topologySpreadConstraints | nindent 8 }}
      {{- end }}
