{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ default "10Gi" .Values.nfs.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Release.Name }}-nfs-server.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}
    helm.sh/chart: {{ include "retrotool-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ .Release.Name }}-{{ .Release.Namespace }}-pv
  storageClassName: ""
  resources:
    requests:
      storage: {{ default "10Gi" .Values.nfs.size }}
{{- end }}
