{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app.kubernetes.io/name: {{ include "retrotool-chart.name" . }}-nfs
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}