kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mongodb-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
