{{- if .Values.database.operator.enabled }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "mongodb-password") | default dict }}
{{- $currentPassword := (b64dec (index $secret "data" "password")) | default (randAlphaNum 24) }}
{{- $password := .Values.database.operator.password | default $currentPassword }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ $password | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-connection
  namespace: {{ .Release.Namespace }}
stringData:
  url: {{ include "mongodb.operator_url" (dict "Values" .Values "password" $password) }}
  oplogUrl: {{ include "mongodb.operator_oplog_url" (dict "Values" .Values "password" $password) }}
{{- end }}