{{- if eq .Values.database.type "operator" }}
{{- $password := randAlphaNum 24 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ $password | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-connection
  namespace: {{ .Release.Namespace }}
stringData:
  url: {{ include "mongodb.operator_url" (dict "Values" .Values "password" $password) }}
  oplogUrl: {{ include "mongodb.operator_oplog_url" (dict "Values" .Values "password" $password) }}
{{- end }}