apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if eq .Values.type "gke" }}
    beta.cloud.google.com/backend-config: '{"ports": {"3000":"{{ .Release.Name }}-backend-config"}}'
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
